version: '3.8'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: diego
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: